### ISSUE TITLE
dump request 

### ISSUE THREAD

**Issue by Wrath-debug** [Unkn0wnH4ck3r/ModernWarfare_H4ck#1]
May I ask you please for the game dumped for those addresses , please ? 
I am trying to update items esp

**Comment by Unkn0wnH4ck3r** [comment]
which address?

**Comment by Unkn0wnH4ck3r** [comment]
ItemBase:
ModernWarfare.exe+2ECBFD3 - 48 33 C4              - xor rax,rsp
ModernWarfare.exe+2ECBFD6 - 48 89 85 50010000     - mov [rbp+00000150],rax
ModernWarfare.exe+2ECBFDD - 48 63 F1              - movsxd  rsi,ecx
ModernWarfare.exe+2ECBFE0 - 4C 8D 2D 3941E80D     - lea r13,[ModernWarfare.exe+10D50120] { ->ItemBase
 }
ModernWarfare.exe+2ECBFE7 - 8B FA                 - mov edi,edx
ModernWarfare.exe+2ECBFE9 - 0F28 F2               - movaps xmm6,xmm2
ModernWarfare.exe+2ECBFEC - 48 8D 0C 76           - lea rcx,[rsi+rsi*2]
ModernWarfare.exe+2ECBFF0 - 48 C1 E1 07           - shl rcx,07 { 7 }
ModernWarfare.exe+2ECBFF4 - 48 03 CF              - add rcx,rdi
ModernWarfare.exe+2ECBFF7 - 48 69 D9 48020000     - imul rbx,rcx,00000248 { 584 }
ModernWarfare.exe+2ECBFFE - 66 42 83 BC 2B C0000000 00 - cmp word ptr [rbx+r13+000000C0],00 { 0 }

ItemMask:
ModernWarfare.exe+2ECBF32 - 48 8D 05 E7ADEB0D     - lea rax,[ModernWarfare.exe+10D86D20] { ->ItemMask
 }
ModernWarfare.exe+2ECBF39 - 48 03 F0              - add rsi,rax
ModernWarfare.exe+2ECBF3C - 0F5B F6               - cvtdq2ps xmm6,xmm6
ModernWarfare.exe+2ECBF3F - 33 DB                 - xor ebx,ebx
ModernWarfare.exe+2ECBF41 - 8B 3E                 - mov edi,[rsi]
ModernWarfare.exe+2ECBF43 - F3 0F59 35 D5CF3801   - mulss xmm6,[ModernWarfare.exe+4258F20] { [0.00] }
ModernWarfare.exe+2ECBF4B - 0F1F 44 00 00         - nop [rax+rax+00]
ModernWarfare.exe+2ECBF50 - 85 FF                 - test edi,edi
ModernWarfare.exe+2ECBF52 - 75 0E                 - jne ModernWarfare.exe+2ECBF62
ModernWarfare.exe+2ECBF54 - FF C3                 - inc ebx
ModernWarfare.exe+2ECBF56 - 83 FB 0C              - cmp ebx,0C { 12 }
ModernWarfare.exe+2ECBF59 - 73 34                 - jae ModernWarfare.exe+2ECBF8F
ModernWarfare.exe+2ECBF5B - 8B 3C 9E              - mov edi,[rsi+rbx*4]
ModernWarfare.exe+2ECBF5E - 85 FF                 - test edi,edi
ModernWarfare.exe+2ECBF60 - 74 F2                 - je ModernWarfare.exe+2ECBF54
ModernWarfare.exe+2ECBF62 - 0FBD CF               - bsr ecx,edi
ModernWarfare.exe+2ECBF65 - 74 05                 - je ModernWarfare.exe+2ECBF6C
ModernWarfare.exe+2ECBF67 - 83 F1 1F              - xor ecx,1F { 31 }
ModernWarfare.exe+2ECBF6A - EB 05                 - jmp ModernWarfare.exe+2ECBF71
ModernWarfare.exe+2ECBF6C - B9 20000000           - mov ecx,00000020 { 32 }
ModernWarfare.exe+2ECBF71 - B8 00000080           - mov eax,80000000 { -2147483648 }
ModernWarfare.exe+2ECBF76 - 8B D3                 - mov edx,ebx
ModernWarfare.exe+2ECBF78 - D3 E8                 - shr eax,cl
ModernWarfare.exe+2ECBF7A - 0F28 D6               - movaps xmm2,xmm6
ModernWarfare.exe+2ECBF7D - C1 E2 05              - shl edx,05 { 5 }
ModernWarfare.exe+2ECBF80 - F7 D0                 - not eax
ModernWarfare.exe+2ECBF82 - 03 D1                 - add edx,ecx
ModernWarfare.exe+2ECBF84 - 23 F8                 - and edi,eax
ModernWarfare.exe+2ECBF86 - 8B CD                 - mov ecx,ebp
ModernWarfare.exe+2ECBF88 - E8 23000000           - call ModernWarfare.exe+2ECBFB0
ModernWarfare.exe+2ECBF8D - EB C1                 - jmp ModernWarfare.exe+2ECBF50
ModernWarfare.exe+2ECBF8F - 48 8B 5C 24 40        - mov rbx,[rsp+40]
ModernWarfare.exe+2ECBF94 - 48 8B 6C 24 48        - mov rbp,[rsp+48]
ModernWarfare.exe+2ECBF99 - 48 8B 74 24 50        - mov rsi,[rsp+50]
ModernWarfare.exe+2ECBF9E - 0F28 74 24 20         - movaps xmm6,[rsp+20]
ModernWarfare.exe+2ECBFA3 - 48 83 C4 30           - add rsp,30 { 48 }
ModernWarfare.exe+2ECBFA7 - 5F                    - pop rdi
ModernWarfare.exe+2ECBFA8 - C3                    - ret

**Comment by Wrath-debug** [comment]
Thanks man, much appreciated , got it working

address as of today
ItemBase -> 0x115E7CD0
ItemMask -> 0x1161E8D0
